# This recipe creates SSL certs that are normally generated by wombat.
# It's intended for use with Test Kitchen.

execute 'Create proper SSL cert to match hostname' do
  command "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj \"/C=US/ST=Washington/L=Seattle/O=SA/CN=#{node['hostname']}.automate-demo.com\" -keyout /etc/ssl/private/#{node['hostname']}.automate-demo.com.key -out /etc/ssl/certs/#{node['hostname']}.automate-demo.com.crt"
  action :run
  not_if "test -f /etc/ssl/certs/#{node['hostname']}.automate-demo.com.crt"
end

execute 'Create crt file for import into Workstation' do
  #command "openssl x509 -outform der -in /etc/ssl/certs/ssl-cert-snakeoil.pem -out /home/ubuntu/#{node['hostname']}.crt"
  command "cp /etc/ssl/certs/#{node['hostname']}.automate-demo.com.crt /home/ubuntu/#{node['hostname']}.automate-demo.com.crt"
  action :run
  not_if "test -f /home/ubuntu/#{node['hostname']}.automate-demo.com.crt"
end
