name 'demo-ecommerce'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo-ecommerce'
long_description 'Installs/Configures demo-ecommerce'
source_url 'https://github.com/chef-cft/demo'
issues_url 'https://github.com/chef-cft/demo/issues'
version '1.0.1'
depends 'java', '= 1.42.0'
